# Generated by Django 5.2.1 on 2026-06-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_job_is_active_alter_jobapplication_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliationitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='associationitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
