# Generated by Django 5.2.1 on 2026-06-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_affiliationitem_title_associationitem_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
