# Generated by Django 5.2.1 on 2026-06-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_teammember_options_teammember_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valueaddedservice',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='valueaddedservice',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
