# Generated by Django 5.2.1 on 2026-06-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_valueaddedservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='key_strengths_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/keystrengths/'),
        ),
    ]
