"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY as an environment variable on the production server.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-+dj&l!#kxmah0g=whf(sb_u*e49_i#=$5oh1b%cbt2$c5)^kqb'  # local dev fallback only
)

# SECURITY WARNING: don't run with debug turned on in production!
# Set DJANGO_DEBUG=False on the production server.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Allowed hosts can be customized per-environment using DJANGO_ALLOWED_HOSTS (comma-separated list).
# In debug mode, we allow localhost/127.0.0.1 as fallbacks.
raw_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
if raw_allowed_hosts:
    ALLOWED_HOSTS = [host.strip() for host in raw_allowed_hosts.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = [
        '82.112.236.35', 'localhost', '127.0.0.1', 
        'api.jdmgroups.com', 'jdm.datamoshtechnology.com', 'www.jdm.datamoshtechnology.com', 
        'jdm.datamoshtechnologies.com', 'www.jdm.datamoshtechnologies.com', 
        'api.datamoshtechnologies.com', 'www.api.datamoshtechnologies.com'
    ]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'clientele',
    # 'gallery',
    'corsheaders'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAdminUser',
    ],
}

# CORS configuration
raw_cors_origins = os.environ.get('DJANGO_CORS_ALLOWED_ORIGINS', '')
if raw_cors_origins:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in raw_cors_origins.split(',') if origin.strip()]
else:
    CORS_ALLOWED_ORIGINS = [
        "http://jdm.datamoshtechnology.com",
        "https://jdm.datamoshtechnology.com",
        "http://jdm.datamoshtechnologies.com",
        "https://jdm.datamoshtechnologies.com",
        "http://api.datamoshtechnologies.com",
        "https://api.datamoshtechnologies.com",
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://jdmgroups.com:3000',
        'https://jdmgroups.com:3000',
        'http://jdmgroups.com',
        'https://jdmgroups.com',
        'http://www.jdmgroups.com',
        'https://www.jdmgroups.com',
    ]

# CSRF configuration
raw_csrf_origins = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
if raw_csrf_origins:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in raw_csrf_origins.split(',') if origin.strip()]
else:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://jdmgroups.com:3000',
        'https://jdmgroups.com',
        'https://www.jdmgroups.com',
        'http://82.112.236.35',
        'https://api.jdmgroups.com'
    ]

# CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'  # or 'None' if cross-site
CSRF_COOKIE_SECURE = not DEBUG   # True in production (HTTPS), False in local dev
SESSION_COOKIE_SECURE = not DEBUG  # True in production (HTTPS), False in local dev
CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_NAME = "csrftoken"

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
# Defaults to SQLite, but dynamically switches to PostgreSQL/MySQL if configuration environment variables are set.
db_engine = os.environ.get('DJANGO_DB_ENGINE', 'sqlite3')

if db_engine != 'sqlite3' or 'DJANGO_DB_NAME' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': f'django.db.backends.{os.environ.get("DJANGO_DB_ENGINE", "postgresql")}',
            'NAME': os.environ.get('DJANGO_DB_NAME'),
            'USER': os.environ.get('DJANGO_DB_USER'),
            'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD'),
            'HOST': os.environ.get('DJANGO_DB_HOST', 'localhost'),
            'PORT': os.environ.get('DJANGO_DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
import os
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
